FROM node:19-alpine as builder

WORKDIR /app

COPY ./client/package.json ./client/package-lock.json ./

RUN npm i

COPY ./client .

ARG VITE_SERVER_BASE_URL

RUN npm run build

FROM nginx:1.24-alpine

COPY ./client/config/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./client/config/nginx/conf.d/* /etc/nginx/conf.d/

COPY --from=builder /app/dist /usr/share/nginx/html