version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        VITE_SERVER_BASE_URL: http://localhost:3002
    ports:
      - "3003:80"

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3002:3000"

    environment:
      ASTEA_INTERN_DB_PASS: ${MOVIES_HUB_DB_PASSWORD}
      ASTEA_INTERN_DB_HOST: db
      ASTEA_INTERN_DB_PORT: 5432
      ASTEA_INTERN_DB_NAME: movies-db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: ${MOVIES_HUB_DB_PASSWORD}
      POSTGRES_DB: movies-db

    volumes:
      - movies-hub-db:/var/lib/postgresql/data

volumes:
  movies-hub-db:
